import BasicExample from "./navbar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body><BasicExample/>{children}</body>
    </html>
  );
}